package com.erdees.farmdataexercise.ui.theme

import androidx.compose.ui.graphics.Color

val Purple200 = Color(0xFFBB86FC)
val Purple500 = Color(0xFF6200EE)
val Purple700 = Color(0xFF3700B3)
val Teal200 = Color(0xFF03DAC5)

val BackgroundColor = Color(0xFFEBEBEB)
val BackgroundColorDarker = Color(0xFFD3D3D3)
val BackgroundColorDarkest = Color(0xFFCECECE)

val OnPrimary = Color(0xFF070707)
val OnPrimaryLight = Color(0xFF1B1B1B)
val OnPrimaryLightest = Color(0xFF363636)

val Yellow100 = Color(0xFFF6F61F)
val Yellow200 = Color(0xFFFFFF9B)
val Yellow300 = Color(0xFFFFFF59)
val Yellow400 = Color(0xFFC9C900)
val Yellow500 = Color(0xFF9B9B00)

val Green100 = Color(0xFFD4F495)
val Green200 = Color(0xFFA3E61D)
val Green300 = Color(0xFFBBEE54)
val Green400 = Color(0xFF7DBB00)
val Green500 = Color(0xFF609100)


val Orange100 = Color(0xFFF6D11F)
val Orange200 = Color(0xFFFFEE9B)
val Orange300 = Color(0xFFFFE359)
val Orange400 = Color(0xFFC9A600)
val Orange500 = Color(0xFF9B8000)

        /**
         * #####  Color Palette by Paletton.com
        #####  Palette URL: http://paletton.com/#uid=51T0u0krXuVcxGVkNwDx1pdGgjr


         *** Primary color:

        shade 0 = #F6F61F = rgb(246,246, 31) = rgba(246,246, 31,1) = rgb0(0.965,0.965,0.122)
        shade 1 = #FFFF9B = rgb(255,255,155) = rgba(255,255,155,1) = rgb0(1,1,0.608)
        shade 2 = #FFFF59 = rgb(255,255, 89) = rgba(255,255, 89,1) = rgb0(1,1,0.349)
        shade 3 = #C9C900 = rgb(201,201,  0) = rgba(201,201,  0,1) = rgb0(0.788,0.788,0)
        shade 4 = #9B9B00 = rgb(155,155,  0) = rgba(155,155,  0,1) = rgb0(0.608,0.608,0)

         *** Secondary color (1):

        shade 0 = #A3E61D = rgb(163,230, 29) = rgba(163,230, 29,1) = rgb0(0.639,0.902,0.114)
        shade 1 = #D4F495 = rgb(212,244,149) = rgba(212,244,149,1) = rgb0(0.831,0.957,0.584)
        shade 2 = #BBEE54 = rgb(187,238, 84) = rgba(187,238, 84,1) = rgb0(0.733,0.933,0.329)
        shade 3 = #7DBB00 = rgb(125,187,  0) = rgba(125,187,  0,1) = rgb0(0.49,0.733,0)
        shade 4 = #609100 = rgb( 96,145,  0) = rgba( 96,145,  0,1) = rgb0(0.376,0.569,0)

         *** Secondary color (2):

        shade 0 = #F6D11F = rgb(246,209, 31) = rgba(246,209, 31,1) = rgb0(0.965,0.82,0.122)
        shade 1 = #FFEE9B = rgb(255,238,155) = rgba(255,238,155,1) = rgb0(1,0.933,0.608)
        shade 2 = #FFE359 = rgb(255,227, 89) = rgba(255,227, 89,1) = rgb0(1,0.89,0.349)
        shade 3 = #C9A600 = rgb(201,166,  0) = rgba(201,166,  0,1) = rgb0(0.788,0.651,0)
        shade 4 = #9B8000 = rgb(155,128,  0) = rgba(155,128,  0,1) = rgb0(0.608,0.502,0)


        #####  Generated by Paletton.com (c) 2002-2014>*/